### ISSUE TITLE
Shopify Liquid extension requires VSCode restart for themeCheckNextDevPreview to apply

### ISSUE THREAD

**Issue by albchu** [Shopify/theme-tools#117]
**Describe the bug**
When devs install the Shopify Liquid vscode extension from the marketplace, they cannot apply the setting to immediately access the new features. VSCode requires a restart first.

```json
  "shopifyLiquid.themeCheckNextDevPreview": true,
```

**Expected behaviour**
Dev preview functionality should activate when the extension config changes.

**Actual behaviour**
Dev preview functionality only activates after a VSCode restart

**Debugging information**
 - OS: Mac
 - OS Version: 13.5.1
 - VSCode extension version:

**Comment by charlespwd** [comment]
It feels like it's true. Something sus going on.
