### ISSUE TITLE
Issue with `cursor-offset` CLI option in Prettier v3 (breaks in JsPrettier for Sublime Text)

### ISSUE THREAD

**Issue by nikitaourazbaev** [Shopify/theme-tools#145]
**Describe the bug**
When using the plugin with Prettier v3 CLI and passing the `--cursor-offset` option, Prettier exits with an error and does not format the file. This breaks JsPrettier for Sublime Text and potentially other code editor integrations.

This worked fine with Prettier v2.

**Debugging information**
 - macOS Ventura 13.6
 - @shopify/prettier-plugin-liquid 1.3.0
 - Prettier 3.0.3
 - node 18.17.1
 - npm 9.6.7

**Additional context**
Here is the terminal output from running prettier with and without the option

```console
$ prettier --write test.liquid
test.liquid 34ms

$ prettier --write test.liquid --cursor-offset 10
test.liquid
[error] test.liquid: TypeError: Cannot read properties of undefined (reading 'start')
[error]     at locStart (/Users/example-user/Code/prettier-test/node_modules/@shopify/prettier-plugin-liquid/dist/utils.js:9:26)
[error]     at nodeContainsCursor (file:///Users/example-user/.local/share/nvm/v18.17.1/lib/node_modules/prettier/index.mjs:18081:40)
[error]     at isMatchedNode (file:///Users/example-user/.local/share/nvm/v18.17.1/lib/node_modules/prettier/index.mjs:17198:64)
[error]     at getChildren (file:///Users/example-user/.local/share/nvm/v18.17.1/lib/node_modules/prettier/index.mjs:17207:16)
[error]     at getChildren.next (<anonymous>)
[error]     at getDescendants (file:///Users/example-user/.local/share/nvm/v18.17.1/lib/node_modules/prettier/index.mjs:17216:16)
[error]     at getDescendants.next (<anonymous>)
[error]     at getCursorNode (file:///Users/example-user/.local/share/nvm/v18.17.1/lib/node_modules/prettier/index.mjs:18083:14)
[error]     at coreFormat (file:///Users/example-user/.local/share/nvm/v18.17.1/lib/node_modules/prettier/index.mjs:18109:23)
[error]     at async formatWithCursor (file:///Users/example-user/.local/share/nvm/v18.17.1/lib/node_modules/prettier/index.mjs:18309:14)
```

It’s possible to work around this in Sublime Text by adding `"disable_prettier_cursor_offset": true` to JsPrettier’s preferences but then cursor position is not maintained after formatting, so it would be nice if this could be addressed if possible.

**Comment by charlespwd** [comment]
Found it. Fix incoming :) Thanks for reporting!

**Comment by charlespwd** [comment]
Try it out in @shopify/prettier-plugin-liquid@1.3.1 :)
