### ISSUE TITLE
Disable auto-formatting and auto-indenting

### ISSUE THREAD

**Issue by MaxDesignFR** [Shopify/theme-tools#169]
Since last update (11 oct. 2023), it seems the Shopify liquid extension is auto-formatting and auto-indenting the code without reason.

I use a region folding extension that wraps the code into regions, and it seems to trigger the file formatting which it never did before the Shopify liquid extension last update. I have `formatOnSave` settings set to false, it's only when I create a region folding through a shortcut that Shopify liquid extension formats the file. I don't see how this issue can be related to the folding extension, beside this extension was not updated recently, nor my settings.

Auto-formatting as shown in this screen recording: https://i.vgy.me/CnQc4e.gif

**Comment by charlespwd** [comment]
See #170, can't reproduce in unit test. Here's me running it in the same file:

https://github.com/Shopify/theme-tools/assets/4990691/3a56eda5-2d6d-4e34-a70e-dbd0283b2c57

**Comment by MaxDesignFR** [comment]
Seems indeed to be the case, I apologize for the time you have put into this. I had no idea `editor.formatOnSave` user settings could be overwritten in such a manner, it makes no sense but I found an issue about that regarding the folding extension: https://github.com/maptz/maptz.vscode.extensions.customfolding/issues/120.
