### ISSUE TITLE
If I'm completing from the middle of a word, I should replace till the end of the word

### ISSUE THREAD

**Issue by charlespwd** [Shopify/theme-tools#239]
**Describe the bug**
If I'm completing from the middle of a word, I should replace till the end of the word

**Source**

```liquid
{{ all_█products }}
```

**Expected behaviour**
If I complete to all_collections, then products should dissapear
```liquid
{{ all_collections█ }}
```

**Actual behaviour**

```liquid
{{ all_collections█products }}
```

**Debugging information**
 - OS [e.g. Windows, Mac, Linux]
 - OS Version
 - Theme Check Version [e.g. 0.1.0]

**Additional context**

**Comment by mgmanzella** [comment]
closing as won't do since typescript doesn't care
