### ISSUE TITLE
Capture tag formatting

### ISSUE THREAD

**Issue by sdn90** [Shopify/theme-tools#259]
A big pain point in developing Shopify themes is that combining `capture` + `render` is the only way for us to have composable copmonents.

From what I've researched, the capture tag doesn't get formatted since it's whitespace sensitive.

Would it be possible to add a comment directive that would handle it?

```diff
  {% # prettier-capture-whitespace-insensitive %}
  {% capture html %}
- <div>Hello</div>
+   <div>Hello</div>
  {% endcapture %}
```

**Comment by charlespwd** [comment]
Ahh it's the cssWhitespace that is the problem. Aight def a bug. 👀

**Comment by sdn90** [comment]
Thanks @charlespwd! Just wanted to mention - all the work you've done on the theme tooling is very much appreciated! It's made such a huge impact on our productivity.

**Comment by charlespwd** [comment]
That's a fair ask and wouldn't make things that complicated internally.

**Comment by charlespwd** [comment]
It is :P But it's not top priority right now. Would accept PRs or would make a good onboarding issue :)

We should create a different issue for that.

**Comment by charlespwd** [comment]
I've opened https://github.com/Shopify/theme-tools/issues/348 with pointers at the end! :pray:
