### ISSUE TITLE
Request textDocument/hover failed.

### ISSUE THREAD

**Issue by sarahmay-harel-authentic** [Shopify/theme-tools#272]
**Describe the bug**
I am getting a slew of these errors everytime my mouse idles for a split second on syntax in a liquid file. One of the features of the extension (among others, which are useful and working) is that it's supposed to provide [documentation on hover](https://shopify.dev/docs/themes/tools/shopify-liquid-vscode#documentation-on-hover). For some reason that's not working for my install and IDE just keeps spamming this error.

**Source**
All liquid files in any of my repos

**Expected behaviour**
Shopify Liquid VS Code extension is supposed to provide [documentation on hover](https://shopify.dev/docs/themes/tools/shopify-liquid-vscode#documentation-on-hover)

**Actual behaviour**
VS Code throws the following error everytime I hover any syntax in a Liquid file: `Request textDocument/hover failed.`
Error output:
```
[Error - 11:27:04 AM] Request textDocument/hover failed.
  Message: Request textDocument/hover failed with message: request to https://raw.githubusercontent.com/Shopify/theme-liquid-docs/main/data/latest.json failed, reason: unable to get local issuer certificate
  Code: -32603 
```
![Screenshot 2024-02-02 at 10 44 13 AM](https://github.com/Shopify/theme-tools/assets/157417011/e23b25f6-49f8-48f3-99db-31930c28742a)

**Debugging information**
 - Mac
 - Ventura 13.5
 - Theme Check Version 2

**Additional context**
Here's my other extensions, in case there's a conflict in there. I already tried:
- Uninstalling and reinstalling Shopify Liquid
- Uninstalling Liquid Languages Support and Shopify Content Schema, testing with those uninstalled, and reinstalling, to no avail
![Screenshot 2024-02-02 at 11 24 23 AM](https://github.com/Shopify/theme-tools/assets/157417011/a7cff9d2-c5c6-4186-9a48-ee8122555cb0)

**Comment by charlespwd** [comment]
Does this still happen? It looks like it might have been caused by a raw.githubusercontent.com outage.

**Comment by sarahmay-harel-authentic** [comment]
hi @charlespwd thanks for getting back to me. Yes this is still happening to me, consistently, every day since I created this ticket.

Screenshot from seconds ago:

![Uploading Screenshot 2024-02-15 at 9.34.47 AM.png…]()

**Comment by sarahmay-harel-authentic** [comment]
sorry, screenshot didn't load. here it is:

![Screenshot 2024-02-15 at 9 36 59 AM](https://github.com/Shopify/theme-tools/assets/157417011/57a97830-f9c0-4ac4-9d92-0853867b9900)

**Comment by charlespwd** [comment]
Alright strange. Looks like your VS Code doesn't want to allow the fetch request to our docsets on raw.githubuser.com.

I'll include the most updated contents of those files as a fallback in our build so that even if the request fails you at least have something to fallback on.

**Comment by sarahmay-harel-authentic** [comment]
Thanks again for your help on this @charlespwd. Yes, I was able to load the URL above in my browser, I got:

`{ "revision": "7c64217076e25564b2580b1370557a0f1dcfb93e" }`

I will check with my IT department to see whether something they're pushing is messing with HTTP certificates. But given that I could load the URL in my browser manually, I suspect it might be something else? Let me know what you think, and again, appreciate your assistance and the fallback support!

**Comment by sarahmay-harel-authentic** [comment]
@wpdev8195 in addition to @charlespwd's fix, we learned that my job was using a certain zero trust SSE which inhibited access to a number of development related things. hope this is helpful for you.

**Comment by wpdev8195** [comment]
@sarahmay-harel-authentic I'm on my own computer, no IT or company restrictions here. I suppose there could, in theory, still be some security setting buried in Windows causing it. Although then I would think the issue would be more common as I have a fairly basic setup.
