### ISSUE TITLE
checkout.liquid objects

### ISSUE THREAD

**Issue by charlespwd** [Shopify/theme-tools#296]
**Describe the bug**
Undefined object, hover, etc does not work for checkout.liquid stuff

We should make it work, but only for `layout/checkout.liquid`.

https://shopify.dev/docs/themes/architecture/layouts/checkout-liquid

**Comment by jagmeetc7** [comment]
One more thing merchant added:

 {{ brand_principles_styles }} . If you look into this, that will be great. I believe this is also required, but somehow Shopify CLI showing undefined object for this.

**Comment by jagmeetc7** [comment]
Hey @charlespwd are you asking if the merchant is following any dev docs for this issue they are dealing with?

**Comment by jagmeetc7** [comment]
@charlespwd merchant responded confirming - Yes, {{ brand_principles_styles }} is user defined variable and values does coming inside it. For now, they’re not using the values coming inside this object. So, they will remove it from their code base.
