### ISSUE TITLE
Section schema, enabled_on templates all, triggers theme-check error

### ISSUE THREAD

**Issue by bigskillet** [Shopify/theme-tools#305]
**Describe the bug**
The section schema below triggers a theme-check error:

**Source**
<img width="647" alt="image" src="https://github.com/Shopify/theme-tools/assets/682013/e09f888b-cafc-4174-9b7d-bb149ea83198">

**Debugging information**
 - Theme Check v2.1.0

**Comment by charlespwd** [comment]
Absolutely right. We forgot to add that to the list in our JSON schema:
https://github.com/Shopify/theme-liquid-docs/blob/main/schemas/theme/section_schema.json#L103-L123

Fixing this...

Thanks for reporting :)

**Comment by charlespwd** [comment]
Should be fixed by https://github.com/Shopify/theme-liquid-docs/pull/476

A restart of your editor should load the latest version of the schema that supports enabled_on "*" / disabled_on "*"
