### ISSUE TITLE
Consider fixing vitest extension problems once and for all

### ISSUE THREAD

**Issue by charlespwd** [Shopify/theme-tools#310]
**Describe the bug**
The extension doesn't support a couple of things:
- Tests of the same name
- `it.each`
- It also breaks if you have two describe with the same name

Wasted like 1-2 hours to realize that there were two `describe('Unit: fileExists', () => {})` in the same test file... The `it` didn't have the same names, the tests names didn't match, and yet the extension broke because of that. 

We should probably setup eslint/tslint/or something that check for problems like this. The VS Code extension didn't provide a useful error message.

**Comment by mgmanzella** [comment]
solved upstream!
