### ISSUE TITLE
Avoid parser blocking scripts by adding `defer` or `async` on this tagtheme-checkParserBlockingScript -- ignores all settings

### ISSUE THREAD

**Issue by Seikilos** [Shopify/theme-tools#316]
**Describe the bug**

The code `<script src="js/chart.js/dist/chart.umd.js"></script>`
causes  `Avoid parser blocking scripts by adding `defer` or `async` on this tagtheme-checkParserBlockingScript`
despite having set these things:

```
{% # theme-check-disable ParserBlockingJavaScript %}
```
and also in `.theme-check.yml`
```
ParserBlockingJavascript:
  enabled: false
  ignore: []

ParserBlockingScriptTag:
  enabled: false
  ignore: []
  
```

**Source**

```liquid
{% # theme-check-disable ParserBlockingJavaScript %}

<script src="js/chart.js/dist/chart.umd.js"></script>

{% # theme-check-enable ParserBlockingJavaScript %}

```

**Expected behaviour**
No warning because at least one setting for muting `ParserBlockingJavaScript` should be honored

**Actual behaviour**
`Avoid parser blocking scripts by adding `defer` or `async` on this tagtheme-checkParserBlockingScript`  Message pops up in visual studio code
![image](https://github.com/Shopify/theme-tools/assets/1260908/d0c3cf7e-3e8b-4253-9cab-522c100ed014)

**Debugging information**
 - Windows 
 - 22H2
 - VS Code 1.86.2
 - Shopify Liquid Extension Version v2.12

**Additional context**

**Comment by Seikilos** [comment]
@charlespwd that did the trick. Thanks for the explanation!

Does this need a vs code update to ship, or is this merely a documentation issue? You could technically add a hint on this to the current docs for all people coming from the VS code extension.

**Comment by mgmanzella** [comment]
closing as wont fix since we're moving forward with theme check written in typescript
