### ISSUE TITLE
HTML Attribute Tab Complete Doesn't Include Equals And Quotes

### ISSUE THREAD

**Issue by domaine-preston** [Shopify/theme-tools#321]
**Is your feature request related to a problem? Please describe.**

When using tab completion for HTML attributes, it doesn't include the equals symbol and quotes. After pressing tab, it looks like this:

`<div class>`
`<p role>`

**Describe the solution you'd like**

I want the equals symbol and the quotes included when using tab completion. The quotes should use the value in VSC's `html.completion.attributeDefaultValue`.

After pressing tab it should look like this:

`<div class=''>`
`<p role=''>`

**Checklist** 
- [x] I have checked and made sure that the proposal adheres to this plugin's [principles](https://github.com/Shopify/prettier-plugin-liquid/blob/main/docs/principles/index.md)

**Additional context**

[This Liquid extension](https://marketplace.visualstudio.com/items?itemName=sissel.shopify-liquid) does it.

**Comment by charlespwd** [comment]
Closing in favour of 345 which has a little more context and breadcrumbs. Still planning on doing it when someone has the capacity.
