### ISSUE TITLE
LiquidHTMLSyntaxError false positive with dynamic attributes 

### ISSUE THREAD

**Issue by alibosworth** [Shopify/theme-tools#335]
**Describe the bug**
It seems like liquid with dynamic attribute name is considered an error

**Source**

```liquid

<img {{ src_attr }}="{{ image | image_url: width: fallback_width }}" />


```

<img width="811" alt="Screenshot 2024-03-28 at 5 33 02 PM" src="https://github.com/Shopify/theme-tools/assets/63747/e4540422-043e-4f37-aec1-9e73188c9b83">

If i change the attribute name to a fixed string, it doesn't error (`img src="..."`)

**Expected behaviour**
Be able to dynamically set html attribute names in liquid

**Actual behaviour**
Theme-check flags it as an error state

**Debugging information**
  -Current Shopify CLI version: 3.58.0

**Comment by charlespwd** [comment]
Confirmed: 
![Uploading image.png…]()
