### ISSUE TITLE
Add a prettier configuration option for `captureWhitespace`

### ISSUE THREAD

**Issue by charlespwd** [Shopify/theme-tools#348]
**Is your feature request related to a problem? Please describe.**

`{% capture var %}` is _technically_ whitespace sensitive. It captures its contents to a variable. Because of this and because we should not to change the semantic meaning of the file with default options, we were forced to use "paste-as-is" logic for the contents of capture tags. 

It has been reported by partners that this level of strictness is not always necessary. You can turn that feature off by using a `white-space: normal` comment above the capture tag, but some folks would want this by default and the other option on-demand. 

@stijns96 proposed having a prettier config that switch the default for that. I like that idea. 

**Describe the solution you'd like**
- Add a new prettier configuration setting that changes the css-whitespace property of the capture tag. Something like this:

```
"captureWhitespace": "strict" | "ignore"
```

Reusing the nomenclature for `htmlWhitespaceSensitivity`. 
- `strict` (default), whitespace is considered significant and will be maintained as pre
- `ignore`, whitespace will not be considered significant. Same as `{% # white-space: normal %}` before capture tags

**Additional context**
Breadcrumbs:
- [Where we define our configuration variables](https://github.com/Shopify/theme-tools/blob/main/packages/prettier-plugin-liquid/src/plugin.ts#L17-L47)
- [Where we would want to switch to a different default for capture tags depending on the config value](https://github.com/Shopify/theme-tools/blob/main/packages/prettier-plugin-liquid/src/printer/preprocess/augment-with-css-properties.ts#L180). Note that that function doesn't accept options like the CssDisplay one above, we should change that.

**Comment by jamesmengo** [comment]
Closed in https://github.com/Shopify/theme-tools/pull/355
