### ISSUE TITLE
theme-check(ValidJSON) mistakenly highlights plural with html as error

### ISSUE THREAD

**Issue by frej-hobbii** [Shopify/theme-tools#357]
**Describe the bug**
When adding a locale that has html content inside, the theme check highlights it as an error, even though it works as expected in liquid.

When combining `_html` postfix to render the locale string as HTML, and a plural, the linting gets confused.

locale
```json
  "ticker": {
    "ticker_physical_stores_html": {
      "one": "<strong>{{ count }} huge</strong> store",
      "other": "<strong>{{ count }} huge</strong> stores"
    }
  },
```

liquid
```html
<div>{{ 'ticker.ticker_physical_stores_html' | t: count: 3 }}</div>
```
<img width="647" alt="Screenshot 2024-05-14 at 10 30 22" src="https://github.com/Shopify/theme-tools/assets/147409734/ec2e9cf9-55f5-493e-880c-976bb7c02d8b">

<img width="627" alt="Screenshot 2024-05-14 at 10 30 40" src="https://github.com/Shopify/theme-tools/assets/147409734/2b258360-7c51-49e9-8e6a-fe230b770d64">

The CLI theme check works as expected, resulting in no errors

<img width="602" alt="Screenshot 2024-05-14 at 10 45 21" src="https://github.com/Shopify/theme-tools/assets/147409734/731509f6-a8fe-4cc7-b9bb-92b4f74d7f78">

**Expected behaviour**
The VS code extension's theme check should work the same as the CLI

**Actual behaviour**
False negative is thrown

**Debugging information**
 - OS: Mac
 - OS Version: Sonoma 14.1.1
 - Theme Check Version `shopify.theme-check-vscode` `Shopify Liquid v2.3.2`

**Additional context**

**Comment by steffenagger** [comment]
@mgmanzella that's not really a solution.
While this _does_ make the theme-check happy, removing the `_html` suffix will result in the html inside the translation-strings being escaped.
Can you elaborate on how to achieve pluralized translations containing html, while making the theme-check happy?
Or perhaps reopen the issue.

[pluralized translations](https://shopify.dev/docs/storefronts/themes/architecture/locales/storefront-locale-files#prevent-translations-from-being-escaped)
[prevent translations from being escaped](https://shopify.dev/docs/storefronts/themes/architecture/locales/storefront-locale-files#prevent-translations-from-being-escaped)
