### ISSUE TITLE
Config files `$schema` validation errors

### ISSUE THREAD

**Issue by madsenmm** [Shopify/theme-tools#367]
**Describe the bug**
When editing typical config files like `.json` or `.rc` files, it throws errors when theres exists `$schema` property in the file.

**Source**
```
Message: Request textDocument/completion failed with message: Cannot read properties of undefined (reading '$schema')
Code: -32603
```

**Expected behaviour**
`$schema` property should be ignored, and only check on `schema` name

**Actual behaviour**
Throws unnecessary error

**Debugging information**
 - OS: Mac
 - OS Version: macOS Sonoma 14.5 (23F79)
 - Theme Check Version: Shopify CLI v. 3.61.0

**Comment by mgmanzella** [comment]
thanks for reporting this issue, to clarify where are you seeing this error and what's happens after receiving it? that looks like an issue with language server and completions erroring out.

sharing exact example files and where they are in your theme directory would be helpful as well for debugging. thanks in advance 🙏

**Comment by tmmgrafikr** [comment]
@mgmanzella Were just editing a `package.json` file, nothing crucial of any format, just noticed the error, because there wre defined a `$schema` property, for JSON Schema helpers.

**Comment by mgmanzella** [comment]
got it, thanks for the context!

**Comment by charlespwd** [comment]
Should be fixed with the latest release. Our DocumentSelector was too permissive and was making non-theme files go through our language server. package.json files should never be linted by theme-check or against theme related JSON schemas.
