### ISSUE TITLE
[Wiki] Add an example nvim-lspconfig server configuration for neovim

### ISSUE THREAD

**Issue by slavamak** [Shopify/theme-tools#372]
**Is your feature request related to a problem? Please describe.**

I suggest adding an example nvim-lspconfig server configuration for neovim on [this](https://github.com/Shopify/theme-tools/wiki/Vim-Neovim) wiki page. Using `nvim-lspconfig` is considered the preferred method of adding language server support for Neovim. 

**Describe the solution you'd like**

## [neovim/nvim-lspconfig](https://github.com/neovim/nvim-lspconfig) Configuration

Set up `shopify_theme_ls` with Neovim's built-in LSP, use the following configuration:

```lua
require("lspconfig").shopify_theme_ls.setup {}
```

This setup requires the Shopify CLI, which can be installed via npm:

```sh
npm install -g @shopify/cli
```

Alternatively, to manage the installation of the Shopify CLI using Mason:

```lua
require("mason").setup {}
require("mason-lspconfig").setup {
    automatic_installation = true
}

require("lspconfig").shopify_theme_ls.setup {}
```

**Checklist** 

- [x] I have checked and made sure that the proposal adheres to this plugin's [principles](../../docs/prettier-plugin-liquid/principles/index.md)

**Additional context**
https://github.com/neovim/nvim-lspconfig/pull/3147
https://github.com/mason-org/mason-registry/pull/5689

**Comment by jamesmengo** [comment]
Hey @slavamak,
This looks great! Thank you for the contribution 🫶 

I've updated the wiki + added an attribution to you for contributing the changes. 
Let me know if you'd like me to update anything there related, and thanks again for helping improve out documentation 😸
