### ISSUE TITLE
Avoid line break between consequent variables

### ISSUE THREAD

**Issue by gavar** [Shopify/theme-tools#381]
**Describe the bug**
The plugin breaks the line between consequent variables if there is nothing in between.

**Unformatted source**
```liquid
Hello {{ FirstName }} and {{ LastName }}

Hello {{ FirstName }} {{ LastName }}
```

**Expected output**
```liquid
Hello {{ FirstName }} and {{ LastName }}

Hello {{ FirstName }} {{ LastName }}
```

**Actual output**
```liquid
Hello {{ FirstName }} and {{ LastName }}

Hello {{ FirstName }}
{{ LastName }}
```

**Debugging information**
 - https://shopify.github.io/prettier-plugin-liquid
 - Version 1.0.2

**Comment by mgmanzella** [comment]
👋 closing as won't fix because this is not the intended use of prettier (should be putting text in translations)
