### ISSUE TITLE
shopifyCLIPath doesn't respect locally installed CLI

### ISSUE THREAD

**Issue by texastoland** [Shopify/theme-tools#384]
## Problem

`"shopifyLiquid.languageServerPath": "./node_modules/.bin/shopify"` configuration doesn't work.

## Solution

1. `LanguageClient` needs initialized with `{...serverOptions, options: {cwd: getItFromVSCode()}}`.
2. My second thought is ideally `options.env.PATH` should be prefixed with `./node_modules/.bin` as a best practice to prefer `devDependencies` over global installation.

**Comment by charlespwd** [comment]
The LSP is baked in the extension now. The ruby LSP is no longer maintained or supported.
