### ISSUE TITLE
ValidJson check and autofix behave badly

### ISSUE THREAD

**Issue by trollkotze** [Shopify/theme-tools#408]
**Describe the bug**
If "ValidJson" is enabled, it will remove unnecessary escapes (backslashes) from JSON on "autofix".
That is unnecessary. Those backslashes don't make the JSON invalid.

This would not be so bad, if Shopify did not insert those backslashes when downloading the theme.
Shopify adding those backslashes on every theme download (also with the GitHub integration, with backslashes appearing automatically in commits after settings changes) and theme-check removing them adds a lot of annoying, unnecessary changes in version control.

If "ValidJson" is disabled, **it will completely delete contents of settings_data.json and settings_schema.json and overwrite them with the string "null"**, instead of leaving them alone.
That really sucks.

**Expected**
If "ValidJson" is enabled, it should not remove backslash escapes on autofix which are only unnecessary but don't make the JSON invalid.

If "ValidJson" is disabled, it should leave the settings_data.json and settings_schema.json untouched, **instead of removing all contents and writing 'null' into them.**

**Actual**
If "ValidJson" is enabled, it will remove unnecessary escapes (backslashes) from JSON on "autofix".

If "ValidJson" is disabled, it will completely delete the settings_data.json, instead of leaving it alone.

**Stack trace**
not applicable

**Debugging information**
- OS Linux Mint 20.1
- Version 1.11.0

**Comment by charlespwd** [comment]
ValidJSON no longer autofixes. We leave that to prettier. 

We also have a separate issue tracking the inconsistency of pushing/pulling files.
