### ISSUE TITLE
'endcomment' is not a valid delimiter

### ISSUE THREAD

**Issue by bigskillet** [Shopify/theme-tools#422]
Commenting conditionals throws the error **'endcomment' is not a valid delimiter, use endif**. The error is also logged in the terminal while `shopify theme serve`.

<img width="505" alt="Screen Shot 2022-02-17 at 10 03 41 AM" src="https://user-images.githubusercontent.com/682013/154606050-37836c06-4a98-44a0-9ac8-b58f18005ff1.png">
<img width="531" alt="Screen Shot 2022-02-17 at 7 39 47 PM" src="https://user-images.githubusercontent.com/682013/154606367-d9dc37b5-e352-4e1a-8764-e4ef4456a6e6.png">

**Comment by charlespwd** [comment]
OK so that's unfortunately a Shopify/liquid parser bug we can't fix without breaking backwards compatibility. They already have an open issue that tracks this, so I'm closing this one since it's been open for quite some time and we can't act on it.
