### ISSUE TITLE
Theme Check Bug with AppBlockValidTags

### ISSUE THREAD

**Issue by mgmanzella** [Shopify/theme-tools#83]
## Overview
During a bughunt for theme-tools, a bug was encountered with the "AppBlockValidTags" check. This check notifies about code issues with 'error' level severity.

## Tested against

- VSCode

## Expected Behavior
In a theme, the use of forbidden tags is allowed and only applies to theme app extensions

## Actual Behavior
In a theme, the use of forbidden tags triggers a theme check error

Repro steps:
- Start debugging with theme-tools
- Open Dawn 
- Open templates/gift_card.liquid
- See theme check error for layout

<img width="1028" alt="Screenshot 2023-09-07 at 1 23 05 PM" src="https://github.com/Shopify/theme-tools/assets/18431672/97ef9582-fffe-4650-9233-fd1a0c08d7e5">

**Comment by charlespwd** [comment]
Fixed this is no longer a recommended check
